Logging and di
john01dav/ssmp pull request #2
Opened 2021-06-22 04:50 UTC by TraceLD

2021-06-22 04:53 UTC, TraceLD commented on Ssmp/ConnectedClient.cs
> +                }
This should roughly mimic the behaviour in https://github.com/ModdedMinecraftClub/polychat2/blob/1f0ac35ce1bcd791fa273267a3645c09d81b936f/server/src/main/java/club/moddedminecraft/polychat/server/services/ServerPollerService.java#L25

2021-06-22 23:19 UTC, ImVaskel approved these changes

2021-06-29 02:30 UTC, john01dav requested changes

2021-06-29 02:30 UTC, john01dav commented on Ssmp/ConnectedClient.cs
> +                    _logger.LogWarning("Received EOL while reading message content bytes.");
It might be better to add the result of this (e.g. the connection will be treated as closed, the client most likely disconnected due to a network error), and ideally some way to identify the client (perhaps the IP and port that the connection is/was running over?). Just knowing that something weird happened is much less helpful to an administrator than to be aware of these further details.

2021-06-29 02:30 UTC, john01dav commented on Ssmp/ConnectedClient.cs
> +                //rationale for try/catch: error in the handler should not bring down the entire hosted service;
Good change, I should have thought of this during the review for your previous PR

2021-06-29 02:30 UTC, john01dav commented on Ssmp/ConnectedClient.cs
> +                    _logger.LogWarning("Received EOL while reading length bytes.");
See my comment on line 97

2021-06-29 09:46 UTC, TraceLD commented on Ssmp/ConnectedClient.cs
> +                    _logger.LogWarning("Received EOL while reading message content bytes.");
To the best of my knowledge I can't get the IP/port after the connection has been disposed of (feel free to prove me wrong). I've made the other change.

2021-06-30 17:11 UTC, TraceLD commented on Ssmp/ConnectedClient.cs
> +                    _logger.LogWarning("Received EOL while reading message content bytes.");
@john01dav I have stored the IP as a field as discussed on Discord and tested it.

2021-06-30 19:31 UTC, TraceLD commented on Ssmp/ConnectedClient.cs
> +        public void Dispose()
Put `Dispose()` at the bottom of the file to adhere to the common C# "convention". Convention in quotes since I don't think it's a written rule, but it's what all code that I've seen does.

2021-06-30 19:31 UTC, TraceLD commented on Ssmp/ConnectedClient.cs
> -        public void Dispose()
see https://github.com/john01dav/ssmp/pull/2/files#r661755786

2021-06-30 19:32 UTC, TraceLD commented on Ssmp/Extensions/NetworkStreamExtensions.cs
> +namespace Ssmp.Extensions
Extensions should be in an `Extensions` namespace.

2021-06-30 19:33 UTC, TraceLD commented on Ssmp/CentralServerBackgroundService.cs
> -        public async Task LaunchForUnitTesting(CancellationToken token)
This code was used nowhere so I've removed it.

2021-06-30 21:09 UTC, john01dav requested changes

2021-06-30 21:09 UTC, john01dav commented on Ssmp/CentralServerService.cs
> +    public interface ICentralServerService
Either remove this or actually use it, as discussed in Discord

2021-06-30 21:09 UTC, john01dav commented on Ssmp/ConnectedClient.cs
> +                _ => "Unknown"
Can you do something to print out *something* about this type? Something like Rust's Debug trait (like an interface) which just pretty prints the list of fields and the class name.

2021-06-30 21:09 UTC, john01dav commented on Ssmp/ConnectedClient.cs
> +                    _logger.LogError(
This is an excellent error message

2021-07-02 15:06 UTC, TraceLD commented on Ssmp/CentralServerService.cs
> +    public interface ICentralServerService
It is now actually used.

2021-07-02 15:11 UTC, TraceLD commented on Ssmp/Ssmp.csproj
> -    <PackageReference Include="System.Threading.Channels" Version="5.0.0" />
The package has been targetting .NET 5 (recommended by MS for new packages, since .NET is new .NET Standard) since the last version and that library is part of the standard library starting with .NET Core 3 (IIRC) so there is no need to include it via NuGet.

2021-07-02 21:55 UTC, merged